// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using settAPI.Data;

#nullable disable

namespace settAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425194039_OptionalNavProperties")]
    partial class OptionalNavProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("settAPI.Classes.ActivityPeriod", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("WorkSessionid")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("period_end")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("period_start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("session_id")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("WorkSessionid");

                    b.ToTable("activity_periods", (string)null);
                });

            modelBuilder.Entity("settAPI.Classes.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("settAPI.Classes.AppActivity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Applicationid")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkSessionid")
                        .HasColumnType("integer");

                    b.Property<int?>("applications_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ended_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_foreground")
                        .HasColumnType("boolean");

                    b.Property<int>("session_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("started_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("Applicationid");

                    b.HasIndex("WorkSessionid");

                    b.ToTable("app_activity", (string)null);
                });

            modelBuilder.Entity("settAPI.Classes.Application", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("category")
                        .HasColumnType("text");

                    b.Property<string>("display_name")
                        .HasColumnType("text");

                    b.Property<string>("process_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("settAPI.Classes.WorkSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Workerid")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ended_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("started_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("total_minutes")
                        .HasColumnType("integer");

                    b.Property<int>("worker_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Workerid");

                    b.ToTable("work_session", (string)null);
                });

            modelBuilder.Entity("settAPI.Classes.Worker", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("department")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("settAPI.Classes.ActivityPeriod", b =>
                {
                    b.HasOne("settAPI.Classes.WorkSession", "WorkSession")
                        .WithMany()
                        .HasForeignKey("WorkSessionid");

                    b.Navigation("WorkSession");
                });

            modelBuilder.Entity("settAPI.Classes.AppActivity", b =>
                {
                    b.HasOne("settAPI.Classes.Application", "Application")
                        .WithMany()
                        .HasForeignKey("Applicationid");

                    b.HasOne("settAPI.Classes.WorkSession", "WorkSession")
                        .WithMany()
                        .HasForeignKey("WorkSessionid");

                    b.Navigation("Application");

                    b.Navigation("WorkSession");
                });

            modelBuilder.Entity("settAPI.Classes.WorkSession", b =>
                {
                    b.HasOne("settAPI.Classes.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("Workerid");

                    b.Navigation("Worker");
                });
#pragma warning restore 612, 618
        }
    }
}
